import { chromium } from '@playwright/test';
const b = await chromium.launch({ channel: 'chrome', args: ['--use-angle=d3d11', '--ignore-gpu-blocklist'] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
await ctx.addInitScript(() => { localStorage.setItem('lx_api_mode', 'off'); localStorage.setItem('lx_logged_in', '1'); localStorage.setItem('lx_role', 'staff'); });
const p = await ctx.newPage();
const errs = []; p.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ' ' + m.text().slice(0, 200)); }); p.on('pageerror', (e) => errs.push('pageerror ' + e.message));
await p.goto('http://localhost:4173/landxi/global/index.html?tenant=lx&locale=en');
await p.waitForFunction(() => document.documentElement.dataset.lx === 'ready', null, { timeout: 60000 });
await p.evaluate(async () => { const f = window.__f1d; await f.go('ysykata'); const y = f.scenes.ys; y.frame(); await y.quote(); const done = new Promise((r) => f.stage.root.addEventListener('f1d:gj1-done', r, { once: true })); y.run({ speed: 200 }); await done; });
await p.waitForTimeout(1500);
await p.screenshot({ path: 'shots/f1/D/_tools/smoke-ys.png' });
const hud = await p.locator('#hud').innerText();
await p.click('#ys-next [data-a="open"]');
const dl = p.waitForEvent('download'); await p.click('#ys-next [data-a="csv"]'); const d = await dl; const csvPath = 'shots/f1/D/_tools/' + d.suggestedFilename(); await d.saveAs(csvPath);
await p.waitForTimeout(500);
await p.screenshot({ path: 'shots/f1/D/_tools/smoke-ys-open.png' });
await p.evaluate(() => window.__f1d.go('sokuluk'));
await p.waitForTimeout(1500);
await p.click('#sk-run'); await p.waitForTimeout(800);
await p.screenshot({ path: 'shots/f1/D/_tools/smoke-sk.png' });
console.log(JSON.stringify({ errs, hud, csv: csvPath }, null, 1));
await b.close();
